### ISSUE TITLE
Internal server Error

### ISSUE THREAD

**Issue by h-wata** [sbgisen/kachaka-api-for-openrmf#3]
**概要**
REST_APIを叩くとInternal server Errorが起きる。

```bash
Traceback (most recent call last):
  File "/home/kachaka/.local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/kachaka/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/kachaka/.local/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/home/kachaka/.local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/kachaka/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/kachaka/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/kachaka/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/kachaka/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/kachaka/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/kachaka/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/kachaka/.local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/kachaka/.local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/kachaka/.local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/kachaka/.local/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/home/kachaka/.local/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/kachaka/sbgisen/rest_kachaka_api.py", line 125, in get
    return await run_method_or_404(method)
  File "/home/kachaka/sbgisen/rest_kachaka_api.py", line 88, in run_method_or_404
    return to_dict(response) if to_dict else response
TypeError: 'bool' object is not callable
```

**再現手順**
REST APIを実行しているKachakaにたいして、`GET` `kachaka/get_robot_pose`を実行。

**修正しないとどう困るか**
APIとの通信不可。

**原因**
`to_dict`の関数と変数が同一関数内で呼ばれているため。

**修正案**

**Comment by MikhailBertrand** [comment]
私がエンバグしてました。失礼いたしました。
